[project]
name = "RezoluStock"
version = "0.1.0"
description = "The inventory management system carefully designed and built to optimize your business."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Rezolusoft HQ", email = "info@rezolusoft.com" },
    { name = "Abiodoun Paraiso", email = "contact@abiodoun.dev" }

]
dependencies = [
  "flet==0.28.2",
]

[tool.flet]
org = "com.rezolusoft"
product = "RezoluStock"
company = "Rezolusoft"
copyright = "Copyright (C) 2025 Proudly made with ❤️ by Rezolusoft, Ajdarra, Benin"

[tool.flet.app]
path = "src"

[tool.flet.macos]
entitlement."com.apple.security.files.user-selected.read-write" = true

[tool.uv]
dev-dependencies = [
    "flet[all]==0.28.2",
    "peewee==3.18.2",
    "peewee-migrate==1.13.0",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.28.2"}