from utils.enums import AccountTypeEnums as account
from core.auth.permissions import *


ROLES_PERMISSIONS = {
    account.OWNER.value : {

        ADD_CATEGORY, CHANGE_CATEGORY, DELETE_CATEGORY,
        ADD_PRODUCT, VIEW_PRODUCT, CHANGE_PRODUCT, DELETE_PRODUCT, ARCHIVE_PRODUCT,
        ADD_SALE, VIEW_SALE, CHANGE_SALE, DELETE_SALE, REFUND_SALE, EXPORT_SALE,
        ADD_CUSTOMER, VIEW_CUSTOMER, CHANGE_CUSTOMER, DELETE_CUSTOMER, 
        ADD_USER, VIEW_USER, CHANGE_USER, DELETE_USER, BLOCK_USER,

    },
    account.ADMIN.value :{
        ADD_CATEGORY, VIEW_CATEGORY, CHANGE_CATEGORY, DELETE_CATEGORY,
        ADD_PRODUCT, VIEW_PRODUCT, CHANGE_PRODUCT, DELETE_PRODUCT, ARCHIVE_PRODUCT,
        ADD_SALE, VIEW_SALE, CHANGE_SALE, DELETE_SALE, REFUND_SALE, EXPORT_SALE,
        ADD_CUSTOMER, VIEW_CUSTOMER, CHANGE_CUSTOMER, DELETE_CUSTOMER, 
        ADD_USER, VIEW_USER, CHANGE_USER, DELETE_USER, BLOCK_USER,
    },

    account.SELLER.value :{
        VIEW_CATEGORY,
        VIEW_PRODUCT, 
        ADD_SALE, VIEW_SALE, CHANGE_SALE, DELETE_SALE, REFUND_SALE, EXPORT_SALE,
        ADD_CUSTOMER, VIEW_CUSTOMER, CHANGE_CUSTOMER, DELETE_CUSTOMER, 
    }
}



class AuthorizationService:

    @staticmethod
    def permissions(role):
        return ROLES_PERMISSIONS.get(role, set())



